### ISSUE TITLE
Add ability to add and view class standings to student info application

### ISSUE THREAD

**Issue by Spyboticsguy** [zj-net/WaterSource#8]
- [ ] Add class standings to internal model #5 
- [ ] Add input widget to app layout #6 
- [ ] Connect new app input features to internal model #7

**Comment by Spyboticsguy** [comment]
Redundant issue. Closing.
